PFTApp/Controllers/TraineeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PFTApp.Models;
using PFTApp.DAL;

namespace PFTApp.Controllers
{
    public class TraineeController : Controller
    {
        private PFTContext db = new PFTContext();

        //
        // GET: /Trainee/

        public ActionResult Index()
        {
            return View(db.Trainees.ToList());
        }

        //
        // GET: /Trainee/Details/5

        public ActionResult Details(int id)
        {
            Trainee trainee = db.Trainees.Find(id);
            if (trainee == null)
            {
                return HttpNotFound();
            }
            return View(trainee);
        }

        //
        // GET: /Trainee/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Trainee/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Trainee trainee)
        {
            if (ModelState.IsValid)
            {
                db.Trainees.Add(trainee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(trainee);
        }

        //
        // GET: /Trainee/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Trainee trainee = db.Trainees.Find(id);
            if (trainee == null)
            {
                return HttpNotFound();
            }
            return View(trainee);
        }

        //
        // POST: /Trainee/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Trainee trainee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trainee);
        }

        //
        // GET: /Trainee/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Trainee trainee = db.Trainees.Find(id);
            if (trainee == null)
            {
                return HttpNotFound();
            }
            return View(trainee);
        }

        //
        // POST: /Trainee/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trainee trainee = db.Trainees.Find(id);
            db.Trainees.Remove(trainee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PFTApp/Views/Shared/_Layout.cshtml
@using System.Diagnostics

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div id="logo">
            <h1>PFT</h1>
        </div>
        <nav>
            <ul>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                @{Debug.Write("Pokus o zobrazeni cookie\nAktualni datum: "+DateTime.Now+"\nAktualni datum plus hodina: "+DateTime.Now.AddHours(1)+"\n");}
                @if (Request.Cookies["Authorized"] != null)
                {
                    //DateTime dtCurrentTime = DateTime.Now;
                    //DateTime dtExpired = Convert.ToDateTime(Request.Cookies["Authorized"]["ExpiredTime"]);
                    //if (dtExpired < dtCurrentTime)
                    //{
                    //    Response.Cookies["Authorized"].Expires = DateTime.Now.AddDays(-1);
                    //    Response.Redirect("/Home");
                    //}                    
                    Debug.Write("Expirace cookie: "+Request.Cookies["Authorized"].Expires+"\n");
                    <li>@Html.ActionLink("User", "Details", "Trainee")</li>
                    <li>@Html.ActionLink("Statistics", "Statistics", "Home")</li>
                    <li>@Html.ActionLink("Log out", "Logout", "Account")</li>
                    
                } else
                {
                    <li>@Html.ActionLink("Log in", "Login", "Account")</li>
                }
            </ul>
        </nav>
    </header>
    <article>
        <div id="centrovac">
            <header>
                <h1>@ViewBag.Title</h1>
            </header>
            @RenderSection("featured", required: false)
            <section>
                <div class="container body-content">
                    @RenderBody()
                </div>
            </section>
            <div class="cistic"></div>
        </div>
    </article>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; Pearsonal Fitness Trainer @DateTime.Now.Year</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>